WebApp/Models/EventPlans/EventPlan.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    // Класс, представляющий собой модель записи в таблице Планы событий
    public class EventPlan
    {
        [Key]
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public int EventId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int PlanVolume { get; set; }
        public decimal PlanCost { get; set; }
        public double EconomicEffect { get; set; }
        public int EmployeeId { get; set; }
    }
}

WebApp/Models/EventPlans/EventPlanIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class EventPlanIndexViewModel
    {
        public List<EventPlanViewModel> EventPlanViewModels { get; set; }

        public List<string> EventNames { get; set; }

        public List<string> OrganNames { get; set; }

        public List<string> EmployeesFIOs { get; set; }

        public PageViewModel PageViewModel { get; set; }

        public List<string> FilterEventsNames { get; set; }

        public string FilterEventName { get; set; }

        public List<string> FilterEmplFIOs { get; set; }

        public string FilterEmplFIO { get; set; }

        public List<int> Ids { get; set; }

        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Название организации")]
        public string OrganizationName { get; set; }

        [Display(Name = "Название события")]
        public string EventName { get; set; }

        [Display(Name = "Начало события")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Конец события")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Планируемый объем")]
        public int PlanVolume { get; set; }

        [Display(Name = "Планируемая стоимость")]
        public decimal PlanCost { get; set; }

        [Display(Name = "Экономический эффект")]
        public double EconomicEffect { get; set; }

        [Display(Name = "ФИО сотрудника")]
        public string EmployeeFIO { get; set; }
    }
}

WebApp/Models/EventPlans/EventPlanViewModel.cs
using System;

namespace WebApp.Models
{
    // Класс модели представления записи из таблицы Планы событий
    public class EventPlanViewModel
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public string EventName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int PlanVolume { get; set; }
        public decimal PlanCost { get; set; }
        public double EconomicEffect { get; set; }
        public string EmployeeFIO { get; set; }
    }
}

WebApp/Controllers/EventPlanController.cs
using WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace WebApp.Controllers
{
    public class EventPlanController : Controller
    {
        // Объект контекста данных
        private readonly ApplicationDBContext db;

        public EventPlanController(ApplicationDBContext applicationContext)
        {
            db = applicationContext;
        }

        // Метод получения страницы клиентов.
        [ResponseCache(CacheProfileName = "Cache")]
        public IActionResult Index(int page = 1, string eventName = "Все", string emplFIO = "Все")
        {
            return View(GetViewModel(page, eventName, emplFIO));
        }

        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        public IActionResult AddEventPlan(EventPlanIndexViewModel model)
        {
            ViewData["Message"] = "";
            if (model.PlanVolume <= 0)
            {
                ViewData["Message"] += "Неправильное значение планируемого объема";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else if (model.EconomicEffect <= 0)
            {
                ViewData["Message"] += "Неправильное значение экономического эффекта";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else if (model.PlanCost <= 0)
            {
                ViewData["Message"] += "Неправильное значение планируемой стоимости";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else
            {
                var id = 0;
                if (db.EventPlans.Count() != 0)
                {
                    id = db.EventPlans.Select(item => item.Id).Max();
                }
                id++;
                db.EventPlans.Add(new EventPlan()
                {
                    Id = id,
                    EndDate = model.EndDate,
                    StartDate = model.StartDate,
                    EconomicEffect = model.EconomicEffect,
                    EmployeeId = db.Employees.Where(item => item.FIO == model.EmployeeFIO).First().Id,
                    EventId = db.Events.Where(item => item.Name == model.EventName).First().Id,
                    OrganizationId = db.Organizations.Where(item => item.Name == model.OrganizationName).First().Id,
                    PlanCost = model.PlanCost,
                    PlanVolume = model.PlanVolume
                });
                db.SaveChanges();
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
        }

        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        public IActionResult DeleteEventPlan(EventPlanIndexViewModel model)
        {
            ViewData["Message"] = "";
            var eventPlan = db.EventPlans.Where(item => item.Id == model.Id).FirstOrDefault();
            db.EventPlans.Remove(eventPlan);
            db.SaveChanges();
            return View("~/Views/EventPlan/Index.cshtml", GetViewModel());
        }

        [Authorize(Roles = "Admin, Employee")]
        [HttpPost]
        public IActionResult UpdateEventPlan(EventPlanIndexViewModel model)
        {
            ViewData["Message"] = "";
            if (model.PlanVolume <= 0)
            {
                ViewData["Message"] += "Неправильное значение планируемого объема";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else if (model.EconomicEffect <= 0)
            {
                ViewData["Message"] += "Неправильное значение экономического эффекта";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else if (model.PlanCost <= 0)
            {
                ViewData["Message"] += "Неправильное значение планируемой стоимости";
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel(1));
            }
            else
            {
                var eventPlan = db.EventPlans.Where(item => item.Id == model.Id).FirstOrDefault();
                eventPlan.EconomicEffect = model.EconomicEffect;
                eventPlan.EmployeeId = db.Employees.Where(item => item.FIO == model.EmployeeFIO).First().Id;
                eventPlan.EndDate = model.EndDate;
                eventPlan.EventId = db.Events.Where(item => item.Name == model.EventName).First().Id;
                eventPlan.OrganizationId = db.Organizations.Where(item => item.Name == model.EventName).First().Id;
                eventPlan.PlanCost = model.PlanCost;
                eventPlan.PlanVolume = model.PlanVolume;
                eventPlan.StartDate = model.StartDate;
                db.SaveChanges();
                return View("~/Views/EventPlan/Index.cshtml", GetViewModel());
            }
        }

        private EventPlanIndexViewModel GetViewModel(int page = 1, string eventName = "Все", string emplFIO = "Все")
        {
            int pageSize = 20;
            List<int> Ids = db.EventPlans.Select(item => item.Id).ToList();
            List<EventPlan> eventPlans = db.EventPlans.ToList();
            List<Employee> employees = db.Employees.ToList();
            List<Event> events = db.Events.ToList();
            List<Organization> organizations = db.Organizations.ToList();
            List<EventPlanViewModel> eventPlanViewModels = new List<EventPlanViewModel>();
            foreach (var eventPlan in eventPlans)
            {
                eventPlanViewModels.Add(new EventPlanViewModel()
                {
                    Id = eventPlan.Id,
                    EndDate = eventPlan.EndDate,
                    EconomicEffect = eventPlan.EconomicEffect,
                    EmployeeFIO = employees.Where(item => item.Id == eventPlan.EmployeeId).First().FIO,
                    EventName = events.Where(item => item.Id == eventPlan.EventId).First().Name,
                    OrganizationName = organizations.Where(item => item.Id == eventPlan.OrganizationId).First().Name,
                    PlanCost = eventPlan.PlanCost,
                    PlanVolume = eventPlan.PlanVolume,
                    StartDate = eventPlan.StartDate
                });
            }

            List<string> eventNames = events.Select(item => item.Name).ToList();
            List<string> emplFIOs = employees.Select(item => item.FIO).ToList();
            eventNames.Add("Все");
            emplFIOs.Add("Все");

            if (eventName != "Все")
            {
                eventPlanViewModels = eventPlanViewModels.Where(item => item.EventName == eventName).ToList();
            }
            if (emplFIO != "Все")
            {
                eventPlanViewModels = eventPlanViewModels.Where(item => item.EmployeeFIO == emplFIO).ToList();
            }

            EventPlanIndexViewModel eventPlanIndexViewModel = new EventPlanIndexViewModel()
            {
                EventPlanViewModels = eventPlanViewModels.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                Ids = Ids,
                EmployeesFIOs = employees.Select(item => item.FIO).ToList(),
                EventNames = events.Select(item => item.Name).ToList(),
                OrganNames = organizations.Select(item => item.Name).ToList(),
                PageViewModel = new PageViewModel(eventPlanViewModels.Count, page, pageSize),
                FilterEmplFIOs = emplFIOs,
                FilterEventsNames = eventNames,
            };
            return eventPlanIndexViewModel;
        }
    }
}

WebApp/Views/EventPlan/Index.cshtml
@model WebApp.Models.EventPlanIndexViewModel
@{
    ViewBag.Title = "Таблица запланированных мероприятий";
}
<script>
    function changeAddVisibility() {
        document.getElementById('DeleteEventPlan').style.display = "none";
        document.getElementById('UpdateEventPlan').style.display = "none";
        document.getElementById('AddEventPlan').style.display = "block";
    }
</script>
<script>
    function changeDeleteVisibility() {
        document.getElementById('DeleteEventPlan').style.display = "block";
        document.getElementById('UpdateEventPlan').style.display = "none";
        document.getElementById('AddEventPlan').style.display = "none";
    }
</script>
<script>
    function changeUpdateVisibility() {
        document.getElementById('DeleteEventPlan').style.display = "none";
        document.getElementById('UpdateEventPlan').style.display = "block";
        document.getElementById('AddEventPlan').style.display = "none";
    }
</script>

<H1>@ViewBag.Title:</H1>
<form method="get">
    <div>
        <label class="control-label">Название события:&nbsp;</label>
        <select name="eventName" class="form-control">
            @foreach (var elem in Model.FilterEventsNames)
            {
                <option>@elem</option>
            }
        </select>
    </div>
    <div>
        <label class="control-label">ФИО работника:&nbsp;</label>
        <select name="emplFIO" class="form-control">
            @foreach (var elem in Model.FilterEmplFIOs)
            {
                <option>@elem</option>
            }
        </select>
    </div>
    <br />
    <div>
        <input type="submit" style="border-color:black;" value="Фильтр" class="btn btn-default" />
    </div>
</form>
<br />
<table border="1">
    <thead>
        <tr>
            <td>
                Id
            </td>
            <td>
                Название организации
            </td>
            <td>
                Название события
            </td>
            <td>
                Начало события
            </td>
            <td>
                Конец события
            </td>
            <td>
                Планируемый объем
            </td>
            <td>
                Планируемая стоимость
            </td>
            <td>
                Экономический эффект
            </td>
            <td>
                ФИО работника
            </td>
        </tr>
    </thead>
    @foreach (var elem in Model.EventPlanViewModels)
    {
        <tr>
            <td>
                @elem.Id
            </td>
            <td>
                @elem.OrganizationName
            </td>
            <td>
                @elem.EventName
            </td>
            <td>
                @elem.StartDate
            </td>
            <td>
                @elem.EndDate
            </td>
            <td>
                @elem.PlanVolume
            </td>
            <td>
                @elem.PlanCost
            </td>
            <td>
                @elem.EconomicEffect
            </td>
            <td>
                @elem.EmployeeFIO
            </td>
        </tr>
    }
</table>
<br />
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark" style="border-color:black;">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark" style="border-color:black;">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}
<br />
@if (User.IsInRole("Admin") || User.IsInRole("Employee"))
{
    <div>
        <input type="submit" style="border-color:black;" value="Добавить запись" onclick="changeAddVisibility()" />
        <input type="submit" style="border-color:black;" value="Удалить запись" onclick="changeDeleteVisibility()" />
        <input type="submit" style="border-color:black;" value="Изменить запись" onclick="changeUpdateVisibility()" />
    </div>
    <hr />
    @ViewData["Message"]
    <div>
        <div id="AddEventPlan" style="display:none;">
            @{await Html.RenderPartialAsync("_AddEventPlan");}
        </div>
        <div id="DeleteEventPlan" style="display:none;">
            @{await Html.RenderPartialAsync("_DeleteEventPlan");}
        </div>
        <div id="UpdateEventPlan" style="display:none;">
            @{await Html.RenderPartialAsync("_UpdateEventPlan");}
        </div>
    </div>
}

WebApp/Views/EventPlan/_AddEventPlan.cshtml
@model WebApp.Models.EventPlanIndexViewModel
<h3>
    Добавление записи
</h3>
<hr />
@using (Html.BeginForm("AddEventPlan", "EventPlan", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.OrganizationName)
        <div class="col-md-10">
            <select name="OrganizationName">
                @foreach (var name in Model.OrganNames)
                {
                    <option>@name</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EventName)
        <div class="col-md-10">
            <select name="EventName">
                @foreach (var fio in Model.EventNames)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.StartDate)
        <div class="col-md-10">
            <input type="date" min="2018-01-01" max="2022-01-01" name="StartDate" />
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.PlanVolume)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PlanVolume)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.PlanCost)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PlanCost)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EconomicEffect)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EconomicEffect)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EmployeeFIO)
        <div class="col-md-10">
            <select name="EmployeeFIO">
                @foreach (var fio in Model.EmployeesFIOs)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Добавить" />
        </div>
    </div>
}

WebApp/Views/EventPlan/_DeleteEventPlan.cshtml
@model WebApp.Models.EventPlanIndexViewModel
<h3>
    Удаление записи
</h3>
<hr />
@using (Html.BeginForm("DeleteEventPlan", "EventPlan", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.Id)
        <div class="col-md-10">
            <select name="Id">
                @foreach (var id in Model.Ids)
                {
                    <option>@id</option>
                }
            </select>
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Удалить" />
        </div>
    </div>
}

WebApp/Views/EventPlan/_UpdateEventPlan.cshtml
@model WebApp.Models.EventPlanIndexViewModel
<h3>
    Изменение записи
</h3>
@using (Html.BeginForm("UpdateEventPlan", "EventPlan", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.Id)
        <div class="col-md-10">
            <select name="Id">
                @foreach (var id in Model.Ids)
                {
                    <option>@id</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.OrganizationName)
        <div class="col-md-10">
            <select name="OrganizationName">
                @foreach (var name in Model.OrganNames)
                {
                    <option>@name</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EventName)
        <div class="col-md-10">
            <select name="EventName">
                @foreach (var fio in Model.EventNames)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.StartDate)
        <div class="col-md-10">
            <input type="date" min="2018-01-01" max="2022-01-01" name="StartDate" />
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.PlanVolume)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PlanVolume)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.PlanCost)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PlanCost)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EconomicEffect)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.EconomicEffect)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.EmployeeFIO)
        <div class="col-md-10">
            <select name="EmployeeFIO">
                @foreach (var fio in Model.EmployeesFIOs)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Изменить" />
        </div>
    </div>
}