WebApp/Models/Sources/Source.cs
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    // Класс, представляющий собой модель записи в таблице Источники
    public class Source
    {
        [Key]
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public decimal OrganizationFunds { get; set; }
        public int SuperiorOrganization { get; set; }
        public decimal SuperiorOrganizationFunds { get; set; }
        public decimal MinistryOfEnergyFund { get; set; }
        public decimal RepublicBudget { get; set; }
        public decimal LocalBudget { get; set; }
        public Source(){}
    }
}

WebApp/Models/Sources/SourceIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class SourceIndexViewModel
    {
        public List<SourceViewModel> SourceViewModels { get; set; }

        public PageViewModel PageViewModel { get; set; }

        public List<string> OrganNames { get; set; }

        public List<string> FilterOrganNames { get; set; }

        public string FilterOrganName { get; set; }

        public string FilterSuperOrganName { get; set; }

        public List<int> Ids { get; set; }

        [Display(Name = "Id")]
        public int Id { get; set; }

        [Display(Name = "Название организации")]
        public string OrganizationName { get; set; }

        [Display(Name = "Фонд организации")]
        public decimal OrganizationFunds { get; set; }

        [Display(Name = "Название вышестоящей организации")]
        public string SuperiorOrganizationName { get; set; }

        [Display(Name = "Фонд вышестоящей организации")]
        public decimal SuperiorOrganizationFunds { get; set; }

        [Display(Name = "Фонд Министерства Энергетики")]
        public decimal MinistryOfEnergyFund { get; set; }

        [Display(Name = "Республиканский бюджет")]
        public decimal RepublicBudget { get; set; }

        [Display(Name = "Местный бюджет")]
        public decimal LocalBudget { get; set; }
    }
}

WebApp/Models/Sources/SourceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    // Класс модели представления записи из таблицы Источники
    public class SourceViewModel
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public decimal OrganizationFunds { get; set; }
        public string SuperiorOrganizationName { get; set; }
        public decimal SuperiorOrganizationFunds { get; set; }
        public decimal MinistryOfEnergyFund { get; set; }
        public decimal RepublicBudget { get; set; }
        public decimal LocalBudget { get; set; }
    }
}

WebApp/Controllers/SourceController.cs
using WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    public class SourceController : Controller
    {
        // Объект контекста данных
        private readonly ApplicationDBContext db;

        public SourceController(ApplicationDBContext applicationContext)
        {
            db = applicationContext;
        }

        // Метод получения страницы клиентов.
        [ResponseCache(CacheProfileName = "Cache")]
        public IActionResult Index(int page = 1, string organName = "Все", string superOrganName = "Все")
        {
            return View(GetViewModel(page, organName, superOrganName));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult AddSource(SourceIndexViewModel model)
        {
            ViewData["Message"] = "";
            if (model.OrganizationFunds <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда организации";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.SuperiorOrganizationFunds <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда вышестоящей организации";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.LocalBudget <= 0)
            {
                ViewData["Message"] += "Неправильное значение местного бюджета";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.MinistryOfEnergyFund <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда Министерства Энергетики";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.RepublicBudget <= 0)
            {
                ViewData["Message"] += "Неправильное значение республиканского бюджета";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else
            {
                var id = 0;
                if (db.Sources.Count() != 0)
                {
                    id = db.Sources.Select(item => item.Id).Max();
                }
                id++;   
                db.Sources.Add(new Source()
                {
                    Id = id,
                    SuperiorOrganization = db.Organizations.Where(item => item.Name == model.SuperiorOrganizationName).First().Id,
                    OrganizationFunds = model.OrganizationFunds,
                    LocalBudget = model.LocalBudget,
                    MinistryOfEnergyFund = model.MinistryOfEnergyFund,
                    OrganizationId = db.Organizations.Where(item => item.Name == model.OrganizationName).First().Id,
                    RepublicBudget = model.RepublicBudget,
                    SuperiorOrganizationFunds = model.SuperiorOrganizationFunds
                });
                db.SaveChanges();
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult DeleteSource(SourceIndexViewModel model)
        {
            ViewData["Message"] = "";
            var source = db.Sources.Where(item => item.Id == model.Id).FirstOrDefault();
            db.Sources.Remove(source);
            db.SaveChanges();
            return View("~/Views/Source/Index.cshtml", GetViewModel(1));
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult UpdateSource(SourceIndexViewModel model)
        {
            ViewData["Message"] = "";
            if (model.OrganizationFunds <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда организации";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.SuperiorOrganizationFunds <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда вышестоящей организации";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.LocalBudget <= 0)
            {
                ViewData["Message"] += "Неправильное значение местного бюджета";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.MinistryOfEnergyFund <= 0)
            {
                ViewData["Message"] += "Неправильное значение фонда Министерства Энергетики";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else if (model.RepublicBudget <= 0)
            {
                ViewData["Message"] += "Неправильное значение республиканского бюджета";
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
            else
            {
                var source = db.Sources.Where(item => item.Id == model.Id).FirstOrDefault();
                source.SuperiorOrganization = db.Organizations.Where(item => item.Name == model.SuperiorOrganizationName).First().Id;
                source.OrganizationFunds = model.OrganizationFunds;
                source.LocalBudget = model.LocalBudget;
                source.MinistryOfEnergyFund = model.MinistryOfEnergyFund;
                source.OrganizationId = db.Organizations.Where(item => item.Name == model.OrganizationName).First().Id;
                source.RepublicBudget = model.RepublicBudget;
                source.SuperiorOrganizationFunds = model.SuperiorOrganizationFunds;
                db.SaveChanges();
                return View("~/Views/Source/Index.cshtml", GetViewModel(1));
            }
        }

        private SourceIndexViewModel GetViewModel(int page, string organName = "Все", string superOrganName = "Все")
        {
            int pageSize = 20;
            List<int> Ids = db.Sources.Select(item => item.Id).ToList();
            List<Source> sources = db.Sources.ToList();
            List<Organization> organizations = db.Organizations.ToList();
            List<SourceViewModel> sourceViewModels = new List<SourceViewModel>();
            foreach (var source in sources)
            {
                sourceViewModels.Add(new SourceViewModel()
                {
                    Id = source.Id,
                    LocalBudget = source.LocalBudget,
                    MinistryOfEnergyFund = source.MinistryOfEnergyFund,
                    SuperiorOrganizationFunds = source.SuperiorOrganizationFunds,
                    SuperiorOrganizationName = organizations.Where(item => item.Id == source.SuperiorOrganization).First().Name,
                    OrganizationFunds = source.OrganizationFunds,
                    OrganizationName = organizations.Where(item => item.Id == source.OrganizationId).First().Name,
                    RepublicBudget = source.RepublicBudget
                });
            }

            List<string> organNames = organizations.Select(item => item.Name).ToList();
            organNames.Add("Все");

            if (organName != "Все")
            {
                sourceViewModels = sourceViewModels.Where(item => item.OrganizationName == organName).ToList();
            }
            if (superOrganName != "Все")
            {
                sourceViewModels = sourceViewModels.Where(item => item.SuperiorOrganizationName == superOrganName).ToList();
            }

            SourceIndexViewModel sourceIndexViewModel = new SourceIndexViewModel()
            {
                SourceViewModels = sourceViewModels.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                Ids = Ids,
                OrganNames = organizations.Select(item => item.Name).ToList(),
                PageViewModel = new PageViewModel(sourceViewModels.Count, page, pageSize),
                FilterOrganNames = organNames
            };
            return sourceIndexViewModel;
        }
    }
}

WebApp/Views/Source/Index.cshtml
@model WebApp.Models.SourceIndexViewModel
@{
    ViewBag.Title = "Таблица источников";
}
<script>
    function changeAddVisibility() {
        document.getElementById('DeleteSource').style.display = "none";
        document.getElementById('UpdateSource').style.display = "none";
        document.getElementById('AddSource').style.display = "block";
    }
</script>
<script>
    function changeDeleteVisibility() {
        document.getElementById('DeleteSource').style.display = "block";
        document.getElementById('UpdateSource').style.display = "none";
        document.getElementById('AddSource').style.display = "none";
    }
</script>
<script>
    function changeUpdateVisibility() {
        document.getElementById('DeleteSource').style.display = "none";
        document.getElementById('UpdateSource').style.display = "block";
        document.getElementById('AddSource').style.display = "none";
    }
</script>

<H1>@ViewBag.Title:</H1>
<form method="get">
    <div>
        <label class="control-label">Название организации:&nbsp;</label>
        <select name="organName" class="form-control">
            @foreach (var elem in Model.FilterOrganNames)
            {
                <option>@elem</option>
            }
        </select>
    </div>
    <div>
        <label class="control-label">Название вышестоящей организации:&nbsp;</label>
        <select name="superOrganName" class="form-control">
            @foreach (var elem in Model.FilterOrganNames)
            {
                <option>@elem</option>
            }
        </select>
    </div>
    <br />
    <div>
        <input type="submit" style="border-color:black;" value="Фильтр" class="btn btn-default" />
    </div>
</form>
<br />
<div>
    <table border="1">
        <thead>
            <tr>
                <td>
                    Id
                </td>
                <td>
                    Название организации
                </td>
                <td>
                    Фонд организации
                </td>
                <td>
                    Название вышестоящей организации
                </td>
                <td>
                    Фонд вышестоящей организации
                </td>
                <td>
                    Фонд Министерства Энергетики
                </td>
                <td>
                    Республиканский бюджет
                </td>
                <td>
                    Местный бюджет
                </td>
            </tr>
        </thead>
        @foreach (var elem in Model.SourceViewModels)
        {
            <tr>
                <td>
                    @elem.Id
                </td>
                <td>
                    @elem.OrganizationName
                </td>
                <td>
                    @elem.OrganizationFunds
                </td>
                <td>
                    @elem.SuperiorOrganizationName
                </td>
                <td>
                    @elem.SuperiorOrganizationFunds
                </td>
                <td>
                    @elem.MinistryOfEnergyFund
                </td>
                <td>
                    @elem.RepublicBudget
                </td>
                <td>
                    @elem.LocalBudget
                </td>
            </tr>
        }
    </table>
</div>
@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-outline-dark">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Index"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-outline-dark">
        Вперед
        <i class="glyphicon glyphicon-chevron-right"></i>
    </a>
}
@if (User.IsInRole("Admin"))
{
    <div>
        <input type="submit" value="Добавить запись" onclick="changeAddVisibility()" />
        <input type="submit" value="Удалить запись" onclick="changeDeleteVisibility()" />
        <input type="submit" value="Изменить запись" onclick="changeUpdateVisibility()" />
    </div>
    <hr />
    @ViewData["Message"]
    <div>
        <div id="AddSource" style="display:none;">
            @{await Html.RenderPartialAsync("_AddSource");}
        </div>
        <div id="DeleteSource" style="display:none;">
            @{await Html.RenderPartialAsync("_DeleteSource");}
        </div>
        <div id="UpdateSource" style="display:none;">
            @{await Html.RenderPartialAsync("_UpdateSource");}
        </div>
    </div>
}

WebApp/Views/Source/_AddSource.cshtml
@model WebApp.Models.SourceIndexViewModel
<h3>
    Добавление записи
</h3>
<hr />
@using (Html.BeginForm("AddSource", "Source", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.OrganizationName)
        <div class="col-md-10">
            <select name="OrganizationName">
                @foreach (var fio in Model.OrganNames)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.OrganizationFunds)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.OrganizationFunds)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.SuperiorOrganizationName)
        <div class="col-md-10">
            <select name="SuperiorOrganizationName">
                @foreach (var name in Model.OrganNames)
                {
                    <option>@name</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.SuperiorOrganizationFunds)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.SuperiorOrganizationFunds)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.MinistryOfEnergyFund)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.MinistryOfEnergyFund)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.RepublicBudget)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RepublicBudget)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.LocalBudget)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LocalBudget)
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Добавить" />
        </div>
    </div>
}

WebApp/Views/Source/_DeleteSource.cshtml
@model WebApp.Models.SourceIndexViewModel
<h3>
    Удаление записи
</h3>
<hr />
@using (Html.BeginForm("DeleteSource", "Source", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.Id)
        <div class="col-md-10">
            <select name="Id">
                @foreach (var id in Model.Ids)
                {
                    <option>@id</option>
                }
            </select>
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Удалить" />
        </div>
    </div>
}

WebApp/Views/Source/_UpdateSource.cshtml
@model WebApp.Models.SourceIndexViewModel
<h3>
    Изменение записи
</h3>
@using (Html.BeginForm("UpdateSource", "Source", FormMethod.Post))
{
    <div>
        @Html.LabelFor(m => m.Id)
        <div class="col-md-10">
            <select name="Id">
                @foreach (var id in Model.Ids)
                {
                    <option>@id</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.OrganizationName)
        <div class="col-md-10">
            <select name="OrganizationName">
                @foreach (var fio in Model.OrganNames)
                {
                    <option>@fio</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.OrganizationFunds)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.OrganizationFunds)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.SuperiorOrganizationName)
        <div class="col-md-10">
            <select name="SuperiorOrganizationName">
                @foreach (var name in Model.OrganNames)
                {
                    <option>@name</option>
                }
            </select>
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.SuperiorOrganizationFunds)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.SuperiorOrganizationFunds)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.MinistryOfEnergyFund)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.MinistryOfEnergyFund)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.RepublicBudget)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.RepublicBudget)
        </div>
    </div>
    <div>
        @Html.LabelFor(m => m.LocalBudget)
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.LocalBudget)
        </div>
    </div>
    <div>
        <div>
            <input type="submit" class="btn btn-default" value="Изменить" />
        </div>
    </div>
}